server:
  port: 8085
  servlet:
    context-path: /config-server

spring:
  application:
    name: config-server-poc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alex-CG/microservices-poc.git
          default-label: master
          search-paths: /config